export const BANK_LIST = {
  "notificaciones@bancocuscatlan.com": [
    {
      subject: "Compra con Tarjeta de Credito Titular",
      parseStart:
        "Se ha realizado una compra con su tarjeta titular de Banco CUSCATLAN XXXXXXXXXX",
      parseEnd: ". Consultas al ",
      parser: "parseStrip",
    },
  ],
  "info@baccredomatic.com": [
    {
      subject: "Alerta PRF BAC Credomatic",
      parseStart: "Inicio 3 iconos  ajustables",
      parseEnd: "Fin 3 cubos ajustables",
      stripCard: [
        "Se acaba de realizar una compra con tu tarjeta",
        "</strong>\n",
      ],
      segmentRow: '<tr bgcolor="#F2F2F2">',
      segmentRowAlt: '<tr bgcolor="#F2F2F2">',
      parser: "sections",
    },
  ],
  "ofsrep.ceosmuigw@wellsfargo.com": [
    {
      subject: "Wire Successful (Beneficiary Copy) - CEO Portal Wires Alert",
      stripCard: "3034",
      dateSlice: [
        '<td class="timelabel">Date/Time Stamp:</td><td class="interiorvalue"><span class="bold">',
        " PT</span></td>",
      ],
      amountSlice: [
        '<td class="interiorlabel">Amount: </td><td class="interiorvalue"><span class="bold">',
        "&nbsp;USD</span></td>",
      ],
      placeSlice: "Baires",
      parser: "segments",
      type: "plus",
    },
  ],
};

export const CURRENCY_PARSER = {
  8: "ALL",
  $: "USD",
  "€": "EUR",
};

export const CATEGORIES = {
  "🃏 Miscelánea": 1,
  "🥖 Alimentos": 2,
  "🍣 Restaurante": 3,
  "🏋️‍♂️ Gimnasio": 4,
  "🧼 Belleza": 5,
  "🍾 Salidas": 6,
  "🏂 Experiencias": 7,
  "🚈 Transporte": 8,
  "🛍 Ropa": 9,
  "🏠 Hospedaje": 10,
  "💸 Income": 11,
};

export const PLACE_TO_CAT = {
  Baires: CATEGORIES["💸 Income"],
  "DIGICEL DING*75373953": CATEGORIES["🃏 Miscelánea"],
  "WALMART CONSTITUCION": CATEGORIES["🥖 Alimentos"],
  "LA PAMPA EST.1987 Z.RO": CATEGORIES["🍣 Restaurante"],
  "KENTUCKY FRIED CHICKEN": CATEGORIES["🍣 Restaurante"],
  "GOOGLE *TEMPORARY HOLD": CATEGORIES["🃏 Miscelánea"],
  "NAME-CHEAP.COM* C0IDTO": CATEGORIES["🃏 Miscelánea"],
  "Digicel Ding 75691813": CATEGORIES["🃏 Miscelánea"],
  "SOLUCIONES FINANCIERAS": CATEGORIES["🃏 Miscelánea"],
  "CLARO MI CLARO EXPRESS": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD BPCRZw": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD F2XFKC": CATEGORIES["🃏 Miscelánea"],
  "EL LOMO Y LA AGUJA": CATEGORIES["🍣 Restaurante"],
  "PANDA EXPRESS MULTIPLA": CATEGORIES["🍣 Restaurante"],
  "GO GREEN MULTIPLAZA": CATEGORIES["🍣 Restaurante"],
  "JUAN VALDEZ MULTIPLAZA": CATEGORIES["🍣 Restaurante"],
  "WENDYS 110 GALERIAS": CATEGORIES["🍣 Restaurante"],
  "FRE CREDITO PAGO AUTOM": CATEGORIES["🃏 Miscelánea"],
  "COA*CHEAPOAIR.COM AIR": CATEGORIES["🚈 Transporte"],
  "AIRBNB * HMJC5JMYSP": CATEGORIES["🏠 Hospedaje"],
  "PRADO STA.TECLA 12 COM": CATEGORIES["🃏 Miscelánea"],
  "ALMACENES SIMAN GALERI": CATEGORIES["🃏 Miscelánea"],
  "GALERIAS DON LI": CATEGORIES["🍣 Restaurante"],
  "VIDALS SBELL POS GALER": CATEGORIES["🧼 Belleza"],
  "FCIAS.ECONOMICAS GALER": CATEGORIES["🃏 Miscelánea"],
  "C COMERCIAL  GALERIAS": CATEGORIES["🃏 Miscelánea"],
  "DIGITALOCEAN.COM": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD L8WvzT": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD zZ9FFx": CATEGORIES["🃏 Miscelánea"],
  "LACALACA DOMICILIO": CATEGORIES["🍣 Restaurante"],
  "SUPER SELECTOS": CATEGORIES["🥖 Alimentos"],
  "LAB ANALIZA SAN GABRIE": CATEGORIES["🃏 Miscelánea"],
  "HUNAN EXPRESS MALL SAN": CATEGORIES["🍣 Restaurante"],
  "TEXACO AEROPUERTO TIEN": CATEGORIES["🃏 Miscelánea"],
  "TEXACO RVQ": CATEGORIES["🃏 Miscelánea"],
  "RESTAURANTE PIZQUE": CATEGORIES["🍣 Restaurante"],
  NA: CATEGORIES["🃏 Miscelánea"],
  "BOLD.CO": CATEGORIES["🃏 Miscelánea"],
  DUFRY: CATEGORIES["🃏 Miscelánea"],
  "DUNKIN DONUTS": CATEGORIES["🍣 Restaurante"],
  "URART GUMRUKSUZ MAGAZA": CATEGORIES["🃏 Miscelánea"],
  "MACA KAHVECILIK": CATEGORIES["🃏 Miscelánea"],
  "VEON GEORGIA LLC": CATEGORIES["🃏 Miscelánea"],
  "NIKORA TRADE JSC": CATEGORIES["🃏 Miscelánea"],
  BOLT: CATEGORIES["🚈 Transporte"],
  "BTA GEORGIA LTD": CATEGORIES["🃏 Miscelánea"],
  "SPARTNER LTD": CATEGORIES["🥖 Alimentos"],
  "Botanica LLC": CATEGORIES["🍣 Restaurante"],
  "APPLE.COM/BILL": CATEGORIES["🃏 Miscelánea"],
  "New Yorker (City Mall)": CATEGORIES["🛍 Ropa"],
  "Armani Exchange 1": CATEGORIES["🛍 Ropa"],
  "T AND K RESTAURANTS LT": CATEGORIES["🍣 Restaurante"],
  "HYPERMARKET SABURTALO": CATEGORIES["🃏 Miscelánea"],
  "Yves Rocher (Goodwill": CATEGORIES["🧼 Belleza"],
  "Go-sport": CATEGORIES["🏋️‍♂️ Gimnasio"],
  "Di Roma LLC": CATEGORIES["🍣 Restaurante"],
  "PSP PHARMA LTD": CATEGORIES["🃏 Miscelánea"],
  "FILEBASE.COM": CATEGORIES["🃏 Miscelánea"],
  "OKTOPUS LTD": CATEGORIES["🏋️‍♂️ Gimnasio"],
  "ITALKI HK LIMITED": CATEGORIES["🃏 Miscelánea"],
  FiverrEU: CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD 38CKTx": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD 6wwV6w": CATEGORIES["🃏 Miscelánea"],
  "K AND M RESTORNEBI 1 L": CATEGORIES["🍣 Restaurante"],
  "LLC Faturato": CATEGORIES["🍣 Restaurante"],
  Wolt: CATEGORIES["🍣 Restaurante"],
  "EPHEMIA KHANTADZE": CATEGORIES["🃏 Miscelánea"],
  "Supta Sakhli(NUCUBIDZE": CATEGORIES["🃏 Miscelánea"],
  "PSP 237": CATEGORIES["🃏 Miscelánea"],
  "SABROSO LTD": CATEGORIES["🍣 Restaurante"],
  "GREEN APPLE GEORGIA (P": CATEGORIES["🍣 Restaurante"],
  "Hypermarket Saburtalo": CATEGORIES["🃏 Miscelánea"],
  "BEELINE.GE1": CATEGORIES["🃏 Miscelánea"],
  "Beeline.ge1": CATEGORIES["🃏 Miscelánea"],
  "AIRBNB * HMXXTHYBRM": CATEGORIES["🏠 Hospedaje"],
  "LLC FATURATO": CATEGORIES["🍣 Restaurante"],
  "KIOSK GEORGIA LTD": CATEGORIES["🃏 Miscelánea"],
  "SEGURO FRE CREDITO": CATEGORIES["🃏 Miscelánea"],
  "SPAR 233": CATEGORIES["🥖 Alimentos"],
  "URBAN GARDEN LTD": CATEGORIES["🍣 Restaurante"],
  "ELIT DIVAN LLC": CATEGORIES["🍣 Restaurante"],
  "FOODMART JSC": CATEGORIES["🥖 Alimentos"],
  "LC WAIKIKI GE LTD": CATEGORIES["🛍 Ropa"],
  "3 HAT LTD": CATEGORIES["🃏 Miscelánea"],
  "LTD NUDA": CATEGORIES["🃏 Miscelánea"],
  "SUPTA SAKHLI (MARJANIS": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD KPvP8F": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD wBMSHR": CATEGORIES["🃏 Miscelánea"],
  "LEVAN ADAMIA I/E": CATEGORIES["🃏 Miscelánea"],
  "SPAR 200": CATEGORIES["🥖 Alimentos"],
  PHARMADEPOT: CATEGORIES["🃏 Miscelánea"],
  "URBAN GARDEN LLC": CATEGORIES["🍣 Restaurante"],
  "Supta Sakhli (Marjanis": CATEGORIES["🃏 Miscelánea"],
  "Yves Rocher(Agmasheneb": CATEGORIES["🧼 Belleza"],
  "APPLE.COM BILL": CATEGORIES["🃏 Miscelánea"],
  "AIRBNB * HM24YTCNAK": CATEGORIES["🏠 Hospedaje"],
  "GASTRONOME KITCHEN LTD": CATEGORIES["🍣 Restaurante"],
  "Shps Silk Gastronomi": CATEGORIES["🍣 Restaurante"],
  "Supta Sakhli (sairmis": CATEGORIES["🃏 Miscelánea"],
  "ASPRIA ONLINE LLC": CATEGORIES["🏋️‍♂️ Gimnasio"],
  "SPAR(KAZBEGI)": CATEGORIES["🥖 Alimentos"],
  "TODUA CLINIC": CATEGORIES["🃏 Miscelánea"],
  "Dunkin (Kiosk Georgia": CATEGORIES["🍣 Restaurante"],
  "LINODE . AKAMAI": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD Vz3TC5": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD 8BLTB8": CATEGORIES["🃏 Miscelánea"],
  "PRICELN*IBIS AMSTERDAM": CATEGORIES["💸 Income"],
  gotogate_us_LW8MR2: CATEGORIES["🚈 Transporte"],
  "AIRBNB * HMHZHFBSKK": CATEGORIES["🏠 Hospedaje"],
  "SWISS INTL AIRLINES AG": CATEGORIES["🚈 Transporte"],
  "001 KFC Goodwill": CATEGORIES["🍣 Restaurante"],
  "ZGAPARI LTD": CATEGORIES["🥖 Alimentos"],
  "SPAR 217": CATEGORIES["🥖 Alimentos"],
  "LTD TIKUNA 3": CATEGORIES["🃏 Miscelánea"],
  "Burger King Spl": CATEGORIES["🍣 Restaurante"],
  "NS SCHIPHOL": CATEGORIES["🃏 Miscelánea"],
  "IBIS AMSTERDAM AIRPORT": CATEGORIES["🃏 Miscelánea"],
  SUBWAY: CATEGORIES["🍣 Restaurante"],
  "CCV*Capital Souvenirs": CATEGORIES["🛍 Ropa"],
  Caharo: CATEGORIES["🃏 Miscelánea"],
  "Andreea Aly": CATEGORIES["🍾 Salidas"],
  Balvert: CATEGORIES["🃏 Miscelánea"],
  "HMS Host International": CATEGORIES["🃏 Miscelánea"],
  "0415 - COOP VENEZIA GA": CATEGORIES["🃏 Miscelánea"],
  "RISTORANTE DA GIULIO": CATEGORIES["🍣 Restaurante"],
  "PALAZZO DUCALE": CATEGORIES["🏂 Experiencias"],
  "BAR AMERICANO": CATEGORIES["🍣 Restaurante"],
  "ETRAVELI.Flightmytrip_": CATEGORIES["🃏 Miscelánea"],
  "AIRBNB * HMMBHM3Y3D": CATEGORIES["🏠 Hospedaje"],
  "VITTORIA SAS DI ALESS.": CATEGORIES["🃏 Miscelánea"],
  "UBER <span>&nbsp;</span><span>&nbsp;</span>*TRIP":
    CATEGORIES["🚈 Transporte"],
  "RELAY PARTENZE": CATEGORIES["🃏 Miscelánea"],
  "RELAY MOLO A": CATEGORIES["🃏 Miscelánea"],
  "FOREXCHANGE AL MACCOP": CATEGORIES["🃏 Miscelánea"],
  NLOVNQX58Q4L8YDJ4M: CATEGORIES["🃏 Miscelánea"],
  PUPIRICHIELLO: CATEGORIES["🍣 Restaurante"],
  "GetYourGuide Tickets": CATEGORIES["🏂 Experiencias"],
  "VIVATICKET SPA": CATEGORIES["🏂 Experiencias"],
  "BANDE NERE M1": CATEGORIES["🚈 Transporte"],
  "DECATHLON 00000342": CATEGORIES["🏋️‍♂️ Gimnasio"],
  "ACQUARIO CIVICO": CATEGORIES["🍾 Salidas"],
  "COOPERATIVA FARMACEUTI": CATEGORIES["🃏 Miscelánea"],
  "MAMMINA MILANO S.R.L.": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD wFVJMT": CATEGORIES["🃏 Miscelánea"],
  "CARREFOUR EXPRESS": CATEGORIES["🥖 Alimentos"],
  "CARREFOUR 0033": CATEGORIES["🥖 Alimentos"],
  "FISIC MILANO CLUB ASSO": CATEGORIES["🏋️‍♂️ Gimnasio"],
  "MIDA TICKET DUOMO DI M": CATEGORIES["🚈 Transporte"],
  "OLD WILD WEST MILANO": CATEGORIES["🍣 Restaurante"],
  "HM IT0444": CATEGORIES["🛍 Ropa"],
  "P.TA VENEZIA ATRIO S5": CATEGORIES["🚈 Transporte"],
  "DOLCE BAR SRL": CATEGORIES["🍣 Restaurante"],
  "www.headout.com": CATEGORIES["🃏 Miscelánea"],
  "AIRBNB * HMHAFM592P": CATEGORIES["🏠 Hospedaje"],
  "AUTOGRILL 0547": CATEGORIES["🍣 Restaurante"],
  "ZERO21 SUSHI": CATEGORIES["🍣 Restaurante"],
  FASTTRACK1: CATEGORIES["🃏 Miscelánea"],
  "NAPOLI PIAZZA GARIBALD": CATEGORIES["🍣 Restaurante"],
  "FARMACIA DE BIASI": CATEGORIES["🃏 Miscelánea"],
  "SCAVI DI POMPEI": CATEGORIES["🏂 Experiencias"],
  "EAV CIRCUMVESUVIANA": CATEGORIES["🃏 Miscelánea"],
  "ROADHOUSE NAPOLI STAZI": CATEGORIES["🚈 Transporte"],
  "DCNAM FRANCHISE SRL": CATEGORIES["🃏 Miscelánea"],
  "ROMA TERMINI SELF SERV": CATEGORIES["🚈 Transporte"],
  "SKR GROUP": CATEGORIES["🃏 Miscelánea"],
  "BUFFET FIRENZE S.M.N.": CATEGORIES["🍣 Restaurante"],
  "FIRENZE S.M.N.SELF SER": CATEGORIES["🚈 Transporte"],
  "MAURONE SRL": CATEGORIES["🃏 Miscelánea"],
  "PISA C.LE SERVICE NEW": CATEGORIES["🚈 Transporte"],
  "MCD PISA": CATEGORIES["🍣 Restaurante"],
  "BUFFET PISA": CATEGORIES["🍣 Restaurante"],
  "MC DONALD&#39;S": CATEGORIES["🍣 Restaurante"],
  Flixbus: CATEGORIES["🚈 Transporte"],
  "SAN DONATO M3": CATEGORIES["🚈 Transporte"],
  CIGNA: CATEGORIES["🃏 Miscelánea"],
  DELIVEROO: CATEGORIES["🍣 Restaurante"],
  TERAPIFY: CATEGORIES["🃏 Miscelánea"],
  "AIRBNB * HMK4RD9HS8": CATEGORIES["🏠 Hospedaje"],
  SOLARIS: CATEGORIES["🛍 Ropa"],
  "YVES ROCHER": CATEGORIES["🧼 Belleza"],
  "LA RINASCENTE DUOMO 55": CATEGORIES["🧼 Belleza"],
  "DUOMO M3": CATEGORIES["🚈 Transporte"],
  PEGASUS: CATEGORIES["🚈 Transporte"],
  "AUTOGRILL 0373": CATEGORIES["🍣 Restaurante"],
  MYCHEF: CATEGORIES["🍣 Restaurante"],
  "ISTANBUL S.GOKCEN HP": CATEGORIES["🃏 Miscelánea"],
  "VODAFONE SHOP": CATEGORIES["🃏 Miscelánea"],
  "CONAD BLLOKU": CATEGORIES["🥖 Alimentos"],
  "Farmaci Arnisa": CATEGORIES["🃏 Miscelánea"],
  "PICERI ERA": CATEGORIES["🍣 Restaurante"],
  "ENIELA MINAJ": CATEGORIES["🧼 Belleza"],
  "GOOGLE *CLOUD HCvBwV": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD C3HvCK": CATEGORIES["🃏 Miscelánea"],
  "RHG SHPK": CATEGORIES["🃏 Miscelánea"],
  KFC: CATEGORIES["🍣 Restaurante"],
  "Wise US Inc.": CATEGORIES["🃏 Miscelánea"],
  "CENTROS PENALES OFI CE": CATEGORIES["🃏 Miscelánea"],
  "MUMA BISTRO BAR": CATEGORIES["🍾 Salidas"],
  "MULLIRI <span>&nbsp;</span>VJETER": CATEGORIES["🍣 Restaurante"],
  "VF SHOP RRUGA DIBRES": CATEGORIES["🃏 Miscelánea"],
  "SPAR 1": CATEGORIES["🥖 Alimentos"],
  "BYLIS PHARMA": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD LMTHv7": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD LPPFD6": CATEGORIES["🃏 Miscelánea"],
  "KLEMENT DUKA": CATEGORIES["🃏 Miscelánea"],
  "GLOBAL FAST FOOD ALBAN": CATEGORIES["🍣 Restaurante"],
  REIMAN: CATEGORIES["🛍 Ropa"],
  "DITE E NATE": CATEGORIES["🥖 Alimentos"],
  "ECO MARKET SHPK": CATEGORIES["🥖 Alimentos"],
  "ARGJENDARI DIVA": CATEGORIES["🛍 Ropa"],
  "MON CHERI": CATEGORIES["🍣 Restaurante"],
  "SPAR ALBANIA": CATEGORIES["🥖 Alimentos"],
  "GO TECH NO INT.": CATEGORIES["🃏 Miscelánea"],
  "RO.GAT SECURITY": CATEGORIES["🍾 Salidas"],
  "ROYAL SPA": CATEGORIES["🧼 Belleza"],
  "TECH STORE": CATEGORIES["🃏 Miscelánea"],
  "Linode . Akamai": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD 5C5CWS": CATEGORIES["🃏 Miscelánea"],
  "GOOGLE *CLOUD 5XBwRB": CATEGORIES["🃏 Miscelánea"],
  SHENDEVERE: CATEGORIES["🃏 Miscelánea"],
  "ADIDAS REEBOK": CATEGORIES["🛍 Ropa"],
  OPA: CATEGORIES["🍣 Restaurante"],
  "NBT OIL": CATEGORIES["🍣 Restaurante"],
  "RKS INVEST AG": CATEGORIES["🍣 Restaurante"],
  "UJVARA E DRINIT": CATEGORIES["🍣 Restaurante"],
  HOPS: CATEGORIES["🍾 Salidas"],
  "CITY ART": CATEGORIES["🃏 Miscelánea"],
};
